apiVersion: v1
kind: Service
metadata:
   name: kelp-service
   labels:
     app: kelp-service
      
spec:
  type: LoadBalancer
  ports:
  - name: ccxt-port
    port: 3000
    targetPort: 3000
  - name: kelp-port
    port: 8000
    targetPort: 8000
  selector:
     app: kelp-pod