apiVersion: v1
kind: Service
metadata:
   name: kelp-service
   labels:
     app: kelp-service
      
spec:
  type: ClusterIP #LoadBalancer #use ClusterIP if its not working with ingress
  ports:
  - name: ccxt-port
    port: 3000
    targetPort: 3000
  - name: kelp-port
    port: 80
    targetPort: 80
  selector:
     app: kelp-pod